services:
  web:
    build: .
    ports:
      - '3000:3000'  
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=000000
      - DB_DATABASE=nestjsdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      # 数据库配置（标准多数据库模式）
      - DATABASE_MODE=standard
      - MYSQL_AS_DEFAULT=true
      - MONGODB_FOR_LOGS=true
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nestjs-network

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '000000'
      MYSQL_DATABASE: 'nestjsdb'
      MYSQL_PASSWORD: '000000'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - nestjs-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: 'nestjslogs'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - nestjs-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1000", "--loglevel", "notice"]
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - nestjs-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  nestjs-network:
    driver: bridge
