services:
  web:
    build: .
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=000000
      - DB_DATABASE=nestjsdb
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nestjs-network

  database:
    image: mysql:8.0
    ports:
      - '127.0.0.1:3306:3306' # 只绑定本地
    environment:
      MYSQL_ROOT_PASSWORD: '000000'
      MYSQL_DATABASE: 'nestjsdb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '000000'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - nestjs-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
    driver: local

networks:
  nestjs-network:
    driver: bridge
